Regression scripts as at 21/09

diff --git a/tools/regression/rerun_jikesrvm b/tools/regression/rerun_jikesrvm
--- a/tools/regression/rerun_jikesrvm
+++ b/tools/regression/rerun_jikesrvm
@@ -2,10 +2,13 @@
 
 set -x
 TODAY=$(date +%Y%m%d)
-DATE=${1:-$TODAY}
-TOP=$HOME/tmp/rerun-rvm-$DATE
 
 BIN=$HOME/dacapo_regressions
+. $BIN/config
+
+DATE=${1:-$TODAY}
+SVNDATE=$(date -d $DATE +%Y-%m-%d)
+TOP=$HOME/tmp/rerun-rvm-$DATE
 
 [ -e $TOP ] || mkdir $TOP #|| { echo "Please cleanup $TOP before you re-run"; exit 1; }
 
@@ -24,27 +27,26 @@ fi
 
 (
   cd $TOP
-  for try in 1 2 3 LAST
-  do
-    echo "Building jikesrvm"
-    RVM_CONFIG=FastAdaptiveGenMS
-    $BIN/build_jikesrvm $TOP $RVM_CONFIG &> $TOP/results-$DATE/jikesrvm.build.$try.log
-    export RVM_ROOT=$TOP/rvm_trunk
-    export RVM_BUILD=$RVM_ROOT/builds/$RVM_CONFIG
-    if [ ! -e $RVM_BUILD/JikesRVM ]; then
-      echo "ERROR: JikesRVM failed to build."
-      [ -e $RVM_BUILD ] && rm -rf $RVM_BUILD
-      echo "Build failed on try $try"
-      if [ "$try" = "LAST" ]; then
-        echo "Giving up in disgust"
-        exit 1
+  if [ ! -e $TOP/rvm_trunk/dist/${RVM_CONFIG}_${HOST_TYPE}/JikesRVM ]; then
+    for try in 1 2 3 LAST
+    do
+      echo "Building jikesrvm"
+      $BIN/build_jikesrvm $TOP $RVM_CONFIG "{$SVNDATE}" &> $TOP/results-$DATE/jikesrvm.build.$try.log
+      if [ ! -e $TOP/rvm_trunk/dist/${RVM_CONFIG}_${HOST_TYPE}/JikesRVM ]; then
+        echo "ERROR: JikesRVM failed to build."
+        [ -e $RVM_BUILD ] && rm -rf $RVM_BUILD
+        echo "Build failed on try $try"
+        if [ "$try" = "LAST" ]; then
+          echo "Giving up in disgust"
+          exit 1
+        fi
+      else
+        break;
       fi
-    else
-      break;
-    fi
-  done
-
+    done
+  fi
   cp $BIN/builds/dacapo-$DATE.jar .
+  export RVM_ROOT=$TOP/rvm_trunk
   $BIN/test_dacapo $DATE JIKESRVM
   $BIN/test_dacapo_results results-$DATE
 )
